version: '3'
services:
  web:
    image: nginx:1.21.0
    environment:  # 追加
      TZ: Asia/Tokyo  # 追加
    ports:
      - "8000:80"
    depends_on: # 追加
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: ./docker/php
    environment:  # 追加
      TZ: Asia/Tokyo  # 追加
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini  # 追加
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --default-time-zone=Asia/Tokyo  # 追加
    environment:
      MYSQL_DATABASE: common 
      MYSQL_USER: nobuhiro
      MYSQL_PASSWORD: nobuhiro
      #MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo  # 追加
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
